### ISSUE TITLE
Wither skeletons are not on the glowing entity list [HVII-1.12-1.0.2]

### ISSUE THREAD

**Issue by kirneh** [The-Fireplace/HVII#1]
As the title says wither skeletons are not on the glowing entity list. Still able to do it by editing the config, but not through the in-game menu.

**Comment by The-Fireplace** [comment]
Forge is no longer being supported, if I update this mod it will be rewritten and only support Fabric going forward. [Here's why](https://gist.github.com/The-Fireplace/d092f25e892a46902ecdec68dee2b938).
